name: Bursa Update
on:
  workflow_dispatch:
jobs:
  run-engine:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install yfinance pandas
      - run: python update_data.py
      - run: |
          git config --global user.name "BursaBot"
          git config --global user.email "bot@github.com"
          git add bursa_live_data.csv
          git commit -m "update" || exit 0
          git push
